# name: Parallel Cypress Tests
# # run workflow on git push
# on: [push]
# jobs:
#   test:
#     name: Cypress run
#     runs-on: ubuntu-20.04
#     # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
#     strategy:
#       # when one test fails, DO NOT cancel the other
#       # containers, because this will kill Cypress processes
#       # leaving the Cypress Cloud hanging ...
#       # https://github.com/cypress-io/github-action/issues/48
#       fail-fast: false
#       matrix:
#         # run 3 copies of the current job in parallel
#         containers: [1, 2, 3, 4]
#     steps:
#       - name: Checkout
#         # GitHub Action for running Cypress end-to-end tests
#         uses: actions/checkout@v4
#       # because of "record" and "parallel" parameters
#       # these containers will load balance all found tests among themselves
#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         with:
#           command: npm run test
#           record: true
#           parallel: true
#         env:
#           # pass the Cypress Cloud record key as an environment variable
#           CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#           # pass the Cypress Cloud project id as an environment variable
#           CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
#           # Recommended: pass the GitHub token lets this action correctly
#           # determine the unique run id necessary to re-run the checks
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Parallel Cypress Tests

on: [push]

jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run specific spec
        run: node scripts/run-specific-spec.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run --record --parallel --ci-build-id ${{ secrets.GITHUB_TOKEN }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
