name: Parallel Cypress Tests
# run workflow on git push
on: [push]
jobs:
  test:
    name: Cypress run
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        # GitHub Action for running Cypress end-to-end tests
        uses: actions/checkout@v4
      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test
          record: true
          parallel: true
        env:
          # pass the Cypress Cloud record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass the Cypress Cloud project id as an environment variable
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}